'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  CheckCircle,
  AlertCircle,
  TrendingUp,
  Download,
  Plus,
  Zap,
  Target,
  ArrowRight,
  Sparkles,
  Loader2,
  FileText,
  RefreshCw,
  ChevronDown,
  ChevronUp,
} from 'lucide-react'
import jsPDF from 'jspdf'

interface AnalysisData {
  overallScore: number
  matchPercentage: number
  matchedSkills: string[]
  missingSkills: string[]
  matchedExperience: string[]
  gapAreas: string[]
  strengths: string[]
  recommendations: string[]
  summary: string
}

interface ImprovedExperience {
  title: string
  company: string
  duration: string
  achievements: string[]
}

interface Improvement {
  section: string
  original: string
  improved: string
  reason: string
}

interface ImprovedResumeData {
  summary: string
  skills: string[]
  experience: ImprovedExperience[]
  improvements: Improvement[]
  keywordMatches: string[]
  additionalSuggestions: string[]
}

interface ResumeProps {
  data: AnalysisData
  onNewAnalysis: () => void
  resumeText?: string
  jobPosting?: string
}

export default function Resume({ data, onNewAnalysis, resumeText, jobPosting }: ResumeProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [improvedResume, setImprovedResume] = useState<ImprovedResumeData | null>(null)
  const [error, setError] = useState('')
  const [showImprovements, setShowImprovements] = useState(true)

  const generateImprovedResume = async () => {
    if (!resumeText || !jobPosting) {
      setError('Resume and job posting are required to generate improvements')
      return
    }

    // Get API key from localStorage
    const stored = localStorage.getItem('apiKeys')
    let apiKeyConfig = null

    if (stored) {
      try {
        const keys = JSON.parse(stored)
        apiKeyConfig = keys.find((key: { is_active: boolean }) => key.is_active)
      } catch {
        setError('Invalid API key configuration. Please check your Settings.')
        return
      }
    }

    if (!apiKeyConfig) {
      setError('No API key configured. Please add one in Settings.')
      return
    }

    setError('')
    setIsGenerating(true)

    try {
      const response = await fetch('/api/improve-resume', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resume: resumeText,
          jobPosting,
          apiKey: apiKeyConfig.api_key,
          provider: apiKeyConfig.provider,
          modelName: apiKeyConfig.model_name,
          analysisData: data,
        }),
      })

      const result = await response.json()

      if (!response.ok) {
        setError(result.error || 'Failed to generate improved resume')
        return
      }

      setImprovedResume(result)
    } catch (err) {
      setError('An error occurred while generating improvements')
      console.error(err)
    } finally {
      setIsGenerating(false)
    }
  }

  const downloadImprovedResumePDF = () => {
    if (!improvedResume) return

    const doc = new jsPDF()
    const pageHeight = doc.internal.pageSize.getHeight()
    const pageWidth = doc.internal.pageSize.getWidth()
    let yPosition = 20

    const addText = (text: string, fontSize = 12, bold = false, color = [0, 0, 0]) => {
      doc.setFontSize(fontSize)
      if (bold) doc.setFont('Helvetica', 'bold')
      else doc.setFont('Helvetica', 'normal')
      doc.setTextColor(color[0], color[1], color[2])

      const lines = doc.splitTextToSize(text, 180)
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - 20) {
          doc.addPage()
          yPosition = 20
        }
        doc.text(line, 15, yPosition)
        yPosition += fontSize * 0.5
      })
    }

    const addSection = (title: string) => {
      yPosition += 8
      doc.setFontSize(14)
      doc.setFont('Helvetica', 'bold')
      doc.setTextColor(255, 165, 0)
      doc.text(title.toUpperCase(), 15, yPosition)
      yPosition += 2
      doc.setDrawColor(255, 165, 0)
      doc.line(15, yPosition, pageWidth - 15, yPosition)
      yPosition += 8
    }

    // Header
    doc.setFillColor(13, 13, 13)
    doc.rect(0, 0, pageWidth, 25, 'F')
    doc.setTextColor(255, 165, 0)
    doc.setFontSize(16)
    doc.setFont('Helvetica', 'bold')
    doc.text('IMPROVED RESUME - Generated by FITLOOP', 15, 16)
    yPosition = 35

    // Professional Summary
    addSection('Professional Summary')
    addText(improvedResume.summary, 11, false, [60, 60, 60])
    yPosition += 5

    // Skills
    addSection('Skills')
    doc.setTextColor(0, 0, 0)
    const skillsText = improvedResume.skills.join(' • ')
    addText(skillsText, 10, false, [60, 60, 60])
    yPosition += 5

    // Experience
    addSection('Experience')
    improvedResume.experience.forEach((exp) => {
      doc.setFontSize(12)
      doc.setFont('Helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      if (yPosition > pageHeight - 40) {
        doc.addPage()
        yPosition = 20
      }
      doc.text(`${exp.title} at ${exp.company}`, 15, yPosition)
      yPosition += 5
      doc.setFontSize(10)
      doc.setFont('Helvetica', 'italic')
      doc.setTextColor(100, 100, 100)
      doc.text(exp.duration, 15, yPosition)
      yPosition += 6

      exp.achievements.forEach((achievement) => {
        if (yPosition > pageHeight - 15) {
          doc.addPage()
          yPosition = 20
        }
        doc.setFont('Helvetica', 'normal')
        doc.setTextColor(60, 60, 60)
        const lines = doc.splitTextToSize(`• ${achievement}`, 175)
        lines.forEach((line: string) => {
          doc.text(line, 18, yPosition)
          yPosition += 5
        })
      })
      yPosition += 4
    })

    // Keywords section
    if (improvedResume.keywordMatches.length > 0) {
      addSection('Incorporated Keywords')
      addText(improvedResume.keywordMatches.join(', '), 10, false, [60, 60, 60])
    }

    doc.save('improved-resume.pdf')
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-accent'
    if (score >= 60) return 'text-yellow-500'
    return 'text-red-500'
  }

  const getScoreLabel = (score: number) => {
    if (score >= 80) return 'EXCELLENT'
    if (score >= 60) return 'GOOD'
    return 'NEEDS IMPROVEMENT'
  }

  const getScoreBorder = (score: number) => {
    if (score >= 80) return 'border-accent/50'
    if (score >= 60) return 'border-yellow-500/50'
    return 'border-red-500/50'
  }

  const downloadPDF = () => {
    const doc = new jsPDF()
    const pageHeight = doc.internal.pageSize.getHeight()
    let yPosition = 20

    const addText = (text: string, fontSize = 12, bold = false) => {
      doc.setFontSize(fontSize)
      if (bold) doc.setFont('Helvetica', 'bold')
      else doc.setFont('Helvetica', 'normal')

      const lines = doc.splitTextToSize(text, 180)
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - 10) {
          doc.addPage()
          yPosition = 20
        }
        doc.text(line, 15, yPosition)
        yPosition += 8
      })
    }

    const addSection = (title: string, items: string[]) => {
      yPosition += 5
      addText(title, 14, true)
      items.forEach((item) => {
        addText(`• ${item}`, 11)
      })
    }

    doc.setFillColor(13, 13, 13)
    doc.rect(0, 0, 210, 30, 'F')
    doc.setTextColor(255, 165, 0)
    addText('FITLOOP — Analysis Report', 18, true)
    yPosition = 40

    doc.setTextColor(0, 0, 0)

    addText(`Overall Compatibility: ${data.overallScore}%`, 16, true)
    addText(`Status: ${getScoreLabel(data.overallScore)}`, 12)
    yPosition += 10

    addSection('Analysis Summary', [data.summary])

    if (data.matchedSkills.length > 0) {
      addSection('Matched Skills', data.matchedSkills)
    }

    if (data.missingSkills.length > 0) {
      addSection('Missing Skills', data.missingSkills)
    }

    if (data.strengths.length > 0) {
      addSection('Your Strengths', data.strengths)
    }

    if (data.recommendations.length > 0) {
      addSection('Recommendations', data.recommendations)
    }

    doc.save('resume-analysis.pdf')
  }

  return (
    <div className="space-y-8">
      {/* Score Card */}
      <div className={`border ${getScoreBorder(data.overallScore)} bg-card p-8`}>
        <div className="flex flex-col md:flex-row items-start justify-between gap-8">
          <div className="flex-1 space-y-4">
            <span className="label-mono text-accent">ANALYSIS COMPLETE</span>
            <h2 className="font-display text-4xl tracking-wider mt-2">RESULTS</h2>
            <p className="font-mono text-xs text-muted-foreground leading-relaxed max-w-xl">{data.summary}</p>
            <div className="flex flex-wrap gap-4 pt-4">
              <Button
                onClick={downloadPDF}
                className="gap-2 bg-accent hover:bg-accent/90 text-accent-foreground font-mono uppercase text-[10px] tracking-widest"
              >
                <Download className="w-4 h-4" />
                DOWNLOAD PDF
              </Button>
              <Button
                onClick={generateImprovedResume}
                disabled={isGenerating || !resumeText || !jobPosting}
                className="gap-2 bg-green-600 hover:bg-green-700 text-white font-mono uppercase text-[10px] tracking-widest"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    GENERATING...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    GENERATE IMPROVED RESUME
                  </>
                )}
              </Button>
              <Button
                onClick={onNewAnalysis}
                variant="outline"
                className="gap-2 bg-transparent border-border/50 hover:border-accent hover:text-accent font-mono uppercase text-[10px] tracking-widest"
              >
                <Plus className="w-4 h-4" />
                NEW ANALYSIS
              </Button>
            </div>
          </div>

          {/* Score Display */}
          <div className="flex flex-col items-center gap-3">
            <div className={`relative w-32 h-32 border-2 ${getScoreBorder(data.overallScore)} flex items-center justify-center`}>
              <div className="text-center">
                <div className={`font-display text-5xl ${getScoreColor(data.overallScore)}`}>
                  {data.overallScore}
                </div>
                <div className="label-mono text-muted-foreground">% MATCH</div>
              </div>
            </div>
            <p className={`label-mono ${getScoreColor(data.overallScore)}`}>
              {getScoreLabel(data.overallScore)}
            </p>
          </div>
        </div>
      </div>

      {/* Matched Skills */}
      {data.matchedSkills.length > 0 && (
        <div className="border border-accent/20 bg-card p-6 space-y-5">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-5 h-5 text-accent" />
            <div>
              <span className="label-mono text-accent">SIGNALS DETECTED</span>
              <h3 className="font-display text-xl tracking-wider mt-1">MATCHED SKILLS</h3>
            </div>
          </div>
          <div className="h-px bg-border/30" />
          <div className="grid md:grid-cols-2 gap-3">
            {data.matchedSkills.map((skill, i) => (
              <div key={i} className="bg-accent/5 border border-accent/20 px-4 py-2.5 font-mono text-xs text-accent">
                {skill}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Missing Skills */}
      {data.missingSkills.length > 0 && (
        <div className="border border-yellow-500/20 bg-card p-6 space-y-5">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-yellow-500" />
            <div>
              <span className="label-mono text-yellow-500">GAPS IDENTIFIED</span>
              <h3 className="font-display text-xl tracking-wider mt-1">MISSING SKILLS</h3>
            </div>
          </div>
          <p className="font-mono text-xs text-muted-foreground">These skills are critical for the role and absent from your resume:</p>
          <div className="h-px bg-border/30" />
          <div className="grid md:grid-cols-2 gap-3">
            {data.missingSkills.map((skill, i) => (
              <div key={i} className="bg-yellow-500/5 border border-yellow-500/20 px-4 py-2.5 font-mono text-xs text-yellow-500">
                {skill}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Strengths */}
      {data.strengths.length > 0 && (
        <div className="border border-border/50 bg-card p-6 space-y-5">
          <div className="flex items-center gap-3">
            <TrendingUp className="w-5 h-5 text-accent" />
            <div>
              <span className="label-mono text-accent">SIGNAL STRENGTH</span>
              <h3 className="font-display text-xl tracking-wider mt-1">YOUR STRENGTHS</h3>
            </div>
          </div>
          <div className="h-px bg-border/30" />
          <ul className="space-y-3">
            {data.strengths.map((strength, i) => (
              <li key={i} className="flex gap-3">
                <ArrowRight className="w-4 h-4 text-accent flex-shrink-0 mt-0.5" />
                <span className="font-mono text-xs text-muted-foreground">{strength}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Gap Areas */}
      {data.gapAreas.length > 0 && (
        <div className="border border-border/50 bg-card p-6 space-y-5">
          <div className="flex items-center gap-3">
            <Target className="w-5 h-5 text-accent" />
            <div>
              <span className="label-mono text-accent">IMPROVEMENT AREAS</span>
              <h3 className="font-display text-xl tracking-wider mt-1">AREAS TO IMPROVE</h3>
            </div>
          </div>
          <div className="h-px bg-border/30" />
          <ul className="space-y-3">
            {data.gapAreas.map((gap, i) => (
              <li key={i} className="flex gap-3">
                <span className="text-accent font-mono text-xs flex-shrink-0 mt-0.5">--</span>
                <span className="font-mono text-xs text-muted-foreground">{gap}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Recommendations */}
      {data.recommendations.length > 0 && (
        <div className="border border-accent/30 bg-accent/5 p-6 space-y-5">
          <div className="flex items-center gap-3">
            <Zap className="w-5 h-5 text-accent" />
            <div>
              <span className="label-mono text-accent">ACTION ITEMS</span>
              <h3 className="font-display text-xl tracking-wider mt-1">RECOMMENDATIONS</h3>
            </div>
          </div>
          <div className="h-px bg-accent/20" />
          <ol className="space-y-3">
            {data.recommendations.map((rec, i) => (
              <li key={i} className="flex gap-3">
                <span className="font-mono text-xs text-accent flex-shrink-0">{String(i + 1).padStart(2, '0')}.</span>
                <span className="font-mono text-xs text-muted-foreground">{rec}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Error Display */}
      {error && (
        <div className="bg-destructive/10 border border-destructive/30 p-4 font-mono text-xs text-destructive">
          {error}
        </div>
      )}

      {/* Improved Resume Section */}
      {improvedResume && (
        <div className="space-y-6">
          {/* Header */}
          <div className="border-2 border-green-500/50 bg-green-500/5 p-8">
            <div className="flex flex-col md:flex-row items-start justify-between gap-6">
              <div className="flex-1 space-y-4">
                <span className="label-mono text-green-500">AI-ENHANCED</span>
                <h2 className="font-display text-4xl tracking-wider mt-2">IMPROVED RESUME</h2>
                <p className="font-mono text-xs text-muted-foreground leading-relaxed max-w-xl">
                  Your resume has been optimized for this specific job posting. Download the improved version or review the changes below.
                </p>
                <div className="flex flex-wrap gap-4 pt-4">
                  <Button
                    onClick={downloadImprovedResumePDF}
                    className="gap-2 bg-green-600 hover:bg-green-700 text-white font-mono uppercase text-[10px] tracking-widest"
                  >
                    <Download className="w-4 h-4" />
                    DOWNLOAD IMPROVED RESUME
                  </Button>
                  <Button
                    onClick={generateImprovedResume}
                    disabled={isGenerating}
                    variant="outline"
                    className="gap-2 bg-transparent border-green-500/50 hover:border-green-500 text-green-500 font-mono uppercase text-[10px] tracking-widest"
                  >
                    {isGenerating ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <RefreshCw className="w-4 h-4" />
                    )}
                    REGENERATE
                  </Button>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <FileText className="w-12 h-12 text-green-500" />
              </div>
            </div>
          </div>

          {/* Improved Professional Summary */}
          <div className="border border-green-500/20 bg-card p-6 space-y-5">
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-green-500" />
              <div>
                <span className="label-mono text-green-500">OPTIMIZED</span>
                <h3 className="font-display text-xl tracking-wider mt-1">PROFESSIONAL SUMMARY</h3>
              </div>
            </div>
            <div className="h-px bg-border/30" />
            <p className="font-mono text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
              {improvedResume.summary}
            </p>
          </div>

          {/* Improved Skills */}
          <div className="border border-green-500/20 bg-card p-6 space-y-5">
            <div className="flex items-center gap-3">
              <CheckCircle className="w-5 h-5 text-green-500" />
              <div>
                <span className="label-mono text-green-500">OPTIMIZED</span>
                <h3 className="font-display text-xl tracking-wider mt-1">SKILLS</h3>
              </div>
            </div>
            <div className="h-px bg-border/30" />
            <div className="flex flex-wrap gap-2">
              {improvedResume.skills.map((skill, i) => (
                <span
                  key={i}
                  className="bg-green-500/10 border border-green-500/30 px-3 py-1.5 font-mono text-xs text-green-500"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>

          {/* Improved Experience */}
          <div className="border border-green-500/20 bg-card p-6 space-y-5">
            <div className="flex items-center gap-3">
              <TrendingUp className="w-5 h-5 text-green-500" />
              <div>
                <span className="label-mono text-green-500">ENHANCED</span>
                <h3 className="font-display text-xl tracking-wider mt-1">EXPERIENCE</h3>
              </div>
            </div>
            <div className="h-px bg-border/30" />
            <div className="space-y-6">
              {improvedResume.experience.map((exp, i) => (
                <div key={i} className="space-y-3">
                  <div>
                    <h4 className="font-mono text-sm font-semibold">{exp.title}</h4>
                    <p className="font-mono text-xs text-muted-foreground">
                      {exp.company} | {exp.duration}
                    </p>
                  </div>
                  <ul className="space-y-2 pl-4">
                    {exp.achievements.map((achievement, j) => (
                      <li key={j} className="flex gap-2">
                        <span className="text-green-500 flex-shrink-0">•</span>
                        <span className="font-mono text-xs text-muted-foreground">{achievement}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Incorporated Keywords */}
          {improvedResume.keywordMatches.length > 0 && (
            <div className="border border-accent/20 bg-card p-6 space-y-5">
              <div className="flex items-center gap-3">
                <Target className="w-5 h-5 text-accent" />
                <div>
                  <span className="label-mono text-accent">ATS OPTIMIZED</span>
                  <h3 className="font-display text-xl tracking-wider mt-1">KEYWORDS INCORPORATED</h3>
                </div>
              </div>
              <p className="font-mono text-xs text-muted-foreground">
                These keywords from the job posting have been naturally incorporated into your improved resume:
              </p>
              <div className="h-px bg-border/30" />
              <div className="flex flex-wrap gap-2">
                {improvedResume.keywordMatches.map((keyword, i) => (
                  <span
                    key={i}
                    className="bg-accent/10 border border-accent/30 px-3 py-1.5 font-mono text-xs text-accent"
                  >
                    {keyword}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Detailed Improvements */}
          {improvedResume.improvements.length > 0 && (
            <div className="border border-border/50 bg-card p-6 space-y-5">
              <button
                onClick={() => setShowImprovements(!showImprovements)}
                className="w-full flex items-center justify-between"
              >
                <div className="flex items-center gap-3">
                  <Sparkles className="w-5 h-5 text-accent" />
                  <div className="text-left">
                    <span className="label-mono text-accent">DETAILED</span>
                    <h3 className="font-display text-xl tracking-wider mt-1">CHANGES MADE</h3>
                  </div>
                </div>
                {showImprovements ? (
                  <ChevronUp className="w-5 h-5 text-muted-foreground" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-muted-foreground" />
                )}
              </button>
              {showImprovements && (
                <>
                  <div className="h-px bg-border/30" />
                  <div className="space-y-6">
                    {improvedResume.improvements.map((improvement, i) => (
                      <div key={i} className="space-y-3 p-4 bg-secondary/50 rounded">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-xs text-accent font-semibold uppercase">
                            {improvement.section}
                          </span>
                        </div>
                        <div className="grid md:grid-cols-2 gap-4">
                          <div className="space-y-2">
                            <span className="label-mono text-red-500">BEFORE</span>
                            <p className="font-mono text-xs text-muted-foreground bg-red-500/5 border border-red-500/20 p-3">
                              {improvement.original}
                            </p>
                          </div>
                          <div className="space-y-2">
                            <span className="label-mono text-green-500">AFTER</span>
                            <p className="font-mono text-xs text-muted-foreground bg-green-500/5 border border-green-500/20 p-3">
                              {improvement.improved}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-start gap-2">
                          <ArrowRight className="w-4 h-4 text-accent flex-shrink-0 mt-0.5" />
                          <p className="font-mono text-xs text-accent">{improvement.reason}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          )}

          {/* Additional Suggestions */}
          {improvedResume.additionalSuggestions.length > 0 && (
            <div className="border border-accent/30 bg-accent/5 p-6 space-y-5">
              <div className="flex items-center gap-3">
                <Zap className="w-5 h-5 text-accent" />
                <div>
                  <span className="label-mono text-accent">PRO TIPS</span>
                  <h3 className="font-display text-xl tracking-wider mt-1">ADDITIONAL SUGGESTIONS</h3>
                </div>
              </div>
              <div className="h-px bg-accent/20" />
              <ul className="space-y-3">
                {improvedResume.additionalSuggestions.map((suggestion, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="font-mono text-xs text-accent flex-shrink-0">{String(i + 1).padStart(2, '0')}.</span>
                    <span className="font-mono text-xs text-muted-foreground">{suggestion}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
